## SPDX-License-Identifier: BSD-2-Clause
## Copyright (c) 2023, Konrad Weihmann
repos:
- repo: local
  hooks:
  - id: sca-integration
    name: SCA tools check
    language: docker_image
    always_run: true
    entry: privkweihmann/sca-container-precommit:latest
